name: Build & Deploy
on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir /var/www/test
            cd /var/www/test
            git clone git@github.com:decourtney/artist_portfolio.git
            echo 'Deployment successful to digital ocean'
